config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'home/index'
  root 'trips#index'

  resources :trips do
    resources :spots, only: [:create, :destroy]
  end

end

app/models/spot.rb
class Spot < ActiveRecord::Base
  belongs_to :trip
  validates :item, presence: { message: "入力してください" }
end

app/models/trip.rb
class Trip < ActiveRecord::Base
	has_many :spots
	validates :title, presence: { message: "入力してください" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

	def create
		@trip = Trip.find(params[:trip_id])
		@spot = @trip.spots.create(spot_params)
		redirect_to trip_path(@trip.id)
	end

	def destroy
		@trip = Trip.find(params[:id])
		@spot.destroy
		redirect_to trips_path
	end

	private

		def spot_params
			params[:spot].permit(:item)
		end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	def index
		@trips = Trip.all
	end

	def show
		@trip = Trip.find(params[:id])
	end

	def new
		@trip = Trip.new
	end

	def create
		@trip = Trip.new(trip_params)
		if @trip.save
			redirect_to trips_path
		else
			render 'new'
		end
	end

	def edit
		@trip = Trip.find(params[:id])
	end

	def update
		@trip = Trip.find(params[:id])
		if @trip.update(trip_params)
			redirect_to trips_path
		else
			render 'edit'
		end
	end

	def destroy
		@trip = Trip.find(params[:id])
		@trip.destroy
		redirect_to trips_path
	end

	private

		def trip_params
			params[:trip].permit(:title)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/home/index.html.erb
<h1>プロジェクト</h1>
<% if user_signed_in? %>
  ユーザー : <strong><%= current_user.name %></strong>.
  <%= link_to "個人設定", edit_user_registration_path, :class => "navbar-link" %> |
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
<% else %>
  <%= link_to "ユーザー登録", new_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "ログイン", new_user_session_path, :class => 'navbar-link' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<% if user_signed_in? %>
  ユーザー : <strong><%= current_user.name %></strong>.
  <%= link_to "個人設定", edit_user_registration_path, :class => "navbar-link" %> |
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
<% else %>
  <%= link_to "ユーザー登録", new_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "ログイン", new_user_session_path, :class => 'navbar-link' %>
<% end %>
<%= yield %>

</body>
</html>

app/views/trips/edit.html.erb
<h1>旅行計画追加</h1>

<%= form_for @trip do |f| %>

<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	<% if @trip.errors.any? %>
	<%= @trip.errors.messages[:title][0] %>
	<% end %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

app/views/trips/index.html.erb
<h1>旅行一覧</h1>

<ul>
	<% @trips.each do |trip| %>
	<li>
		<%= link_to trip.title, trip_path(trip.id) %>
		<%= link_to "[編集]", edit_trip_path(trip.id) %>
		<%= link_to "[削除]", trip_path(trip.id), method: :delete, data: { confirm: "削除しますか？" } %>
	</li>
	<% end %>
</ul>

<p><%= link_to "追加", new_trip_path %></p>

app/views/trips/new.html.erb
<h1>旅行計画追加</h1>

<%= form_for @trip do |f| %>

<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	<% if @trip.errors.any? %>
	<%= @trip.errors.messages[:title][0] %>
	<% end %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

app/views/trips/show.html.erb
<h1><%= @trip.title %></h1>
<p><%= image_tag "jibaku.jpg" %></p>

<ul>
	<% @trip.spots.each do |spot| %>
	<li><%= spot.item %></li>
	<% end %>
	<li>
		<%= form_for [@trip, @trip.spots.build] do |f| %>
		<%= f.text_field :item %>
		<%= f.submit %>
		<% end %>
	</li>
</ul>
<%= link_to "戻る", trips_path %>